### ISSUE TITLE
How does this correspond with the Server repo?

### ISSUE THREAD

**Issue by Viswas-Programs** [SurvivReloaded/survivreloaded-client#1]
Like, if I was new (which I am not), where I would clone this all? all in the main server repo main folder? the "public" folder which contains everything?

**Comment by hsanger** [comment]
You would run this command in the server repo folder:
```
git clone https://github.com/SurvivReloaded/survivreloaded-client public
```

**Comment by Viswas-Programs** [comment]
You mean the main, top level folder, or the public folder?

**Comment by hsanger** [comment]
The main, top level folder.
